[package]
name = "tempest_core"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
tempest_common = { path = "../tempest_common" }
tempest_ecs = { path = "../tempest_ecs" }
tempest_render = { path = "../tempest_render" }
env_logger = "0.10"
log = "0.4"
pollster = "0.2"
winit = "0.28"
