[package]
name = "tempest-ecs-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.30"
quote = "1.0.9"
syn = { version = "2.0.16", features = ["full"] }
lazy_static = "1.4.0"
proc-macro-error = "1.0.4"