[package]
name = "tempest-core"
version = "0.1.0-dev"
edition = "2021"

[dependencies]
tempest-common = { path = "../tempest-common" }
tempest-ecs = { path = "../tempest-ecs" }
tempest-render = { path = "../tempest-render" }
env_logger = "0.10"
log = "0.4"
pollster = "0.2"
winit = "0.28"
